default[:teletraan][:release_version] = "v1.0.1"
default[:teletraan][:agent_version] = "1.2.3"
default[:teletraan][:proto] = "http" 
default[:teletraan][:host] = "127.0.0.1" 
default[:teletraan][:port] = "8080" 